import type { MultiRootAnalysis, ResolutionPlan, UsageReference } from '@animoria/core/contracts';
import type {
  HostCapabilities,
  HostInbound,
  HostOutbound,
  RootCleanupPlan,
  RootCleanupProposal,
  UiPreferences,
} from '@animoria/ui';
import {
  DEFAULT_PREFERENCES,
  LOTTIE_FORMATS,
  buildAnimationPreview,
  validateOutbound,
} from '@animoria/ui';

/**
 * The sandbox's `HostBridge` implementation — Animoria's reference host.
 *
 * ## Why the sandbox is a host and not a special build of the UI
 * It implements the same contract VS Code and JetBrains implement, and it drives the
 * same components through the same messages. The only difference is what it declares
 * it can do. That is the whole design: a harness whose destructive paths are *absent*
 * cannot review the states a real host shows, so the sandbox keeps every screen and
 * turns off one capability.
 *
 * ## `canMutate: false`, enforced in three places
 * 1. **Here.** Every mutating message is refused before it reaches the network, with
 *    a reason the console shows.
 * 2. **In the components.** `canMutate` disables the control and renders the reason
 *    beside it, so the developer sees the disabled state rather than a missing one.
 * 3. **In `vite.config.ts`.** Every non-GET `/api/*` returns 405 regardless of what
 *    any client sends.
 *
 * Three enforcement points for one rule is deliberate. The first is the contract, the
 * second is the affordance, and the third is the guarantee — and only the third
 * survives someone editing this file.
 */

export const SANDBOX_CAPABILITIES: HostCapabilities = {
  canMutate: false,
  canRestore: false,
  // Navigation is a no-op that logs, rather than being declared unavailable: the
  // harness exists to exercise the flows, and a disabled "open reference" would hide
  // the evidence panel's most important affordance from review.
  canRevealInFileManager: false,
  canOpenReference: true,
  // Snippets are generated by Core and shown in the panel — no editor required, so
  // the harness can review the surface the IDEs ship rather than a disabled button.
  canGenerateSnippet: true,
  canCopyToClipboard: true,
  mutationUnavailableReason:
    'This action is unavailable in the Sandbox. The harness is read-only by construction — it exercises every screen without touching the filesystem.',
};

/**
 * `MultiRootAnalysis` as JSON puts it on the wire.
 *
 * Only the part that differs is described: `referenceCounts` is a `Map` in the
 * contract and cannot survive `JSON.stringify`, so the dev bridge sends pairs and the
 * host rebuilds the map.
 */
type WireAnalysis = Omit<MultiRootAnalysis, 'roots'> & {
  readonly roots: readonly (Omit<MultiRootAnalysis['roots'][number], 'analysis'> & {
    readonly analysis: Omit<MultiRootAnalysis['roots'][number]['analysis'], 'referenceCounts'> & {
      readonly referenceCounts?: readonly (readonly [string, number])[];
    };
  })[];
};

/** One line in the harness's event log. Sandbox-only instrumentation. */
export interface SandboxLogEntry {
  readonly at: string;
  readonly direction: 'ui→host' | 'host→ui' | 'refused';
  readonly type: string;
  readonly detail: string;
}

export interface SandboxHostOptions {
  /** Called for every message in either direction, for the harness event console. */
  readonly onLog?: (entry: SandboxLogEntry) => void;
}

/**
 * Serves the shared UI from the read-only dev bridge.
 *
 * Requests go to `/api/*`, which `vite.config.ts` guarantees is GET-only. The
 * analysis is Core's own, computed by a real `WorkspaceIndexer` over the committed
 * fixtures — the harness renders Core's answer rather than a second one invented
 * here, which is what X2 removed.
 */
export class SandboxHost {
  private readonly _listeners = new Set<(message: HostInbound) => void>();
  private readonly _onLog: ((entry: SandboxLogEntry) => void) | undefined;
  private _analysis: MultiRootAnalysis | null = null;
  /**
   * Preferences and dismissals, in `localStorage`.
   *
   * The harness is read-only *about the workspace* — it never touches the developer's
   * files. Its own view state is not the workspace, and persisting it is what lets a
   * reviewer check that a preference survives a reload, which is the behaviour a real
   * host must have.
   */
  private _preferences: UiPreferences = readStored(
    'animoria.sandbox.preferences',
    DEFAULT_PREFERENCES
  );
  private _dismissed = new Set<string>(readStored<string[]>('animoria.sandbox.dismissed', []));

  constructor(options: SandboxHostOptions = {}) {
    this._onLog = options.onLog;
  }

  // ── HostBridge ─────────────────────────────────────────────────────────────

  send(raw: HostOutbound): void {
    const validated = validateOutbound(raw);
    if (!validated.ok) {
      this._log('refused', 'invalid', validated.reason);
      return;
    }
    void this._handle(validated.message);
  }

  subscribe(listener: (message: HostInbound) => void): () => void {
    this._listeners.add(listener);
    return () => {
      this._listeners.delete(listener);
    };
  }

  // ── Internals ──────────────────────────────────────────────────────────────

  private _emit(message: HostInbound): void {
    this._log('host→ui', message.type, '');
    for (const listener of this._listeners) listener(message);
  }

  private _log(direction: SandboxLogEntry['direction'], type: string, detail: string): void {
    this._onLog?.({ at: new Date().toISOString(), direction, type, detail });
  }

  private _refuse(type: string): void {
    this._log('refused', type, SANDBOX_CAPABILITIES.mutationUnavailableReason ?? '');
    this._emit({
      type: 'error',
      message: SANDBOX_CAPABILITIES.mutationUnavailableReason ?? 'Unavailable in the Sandbox.',
      recoverable: true,
    });
  }

  private async _handle(message: HostOutbound): Promise<void> {
    this._log('ui→host', message.type, '');

    switch (message.type) {
      case 'ready':
        this._emit({ type: 'capabilities', capabilities: SANDBOX_CAPABILITIES });
        this._emit({ type: 'preferences', preferences: this._preferences });
        await this._runAnalysis();
        return;

      case 'run-analysis':
        await this._runAnalysis();
        return;

      case 'request-thumbnail': {
        // `MultiRootAnalysis.assets` holds `AttributedAsset` — `{rootId, rootName,
        // asset}` — not bare assets. Reading `.path` off the wrapper produced
        // `undefined` for every asset, so the harness silently showed a placeholder
        // for thumbnails Core had actually rendered.
        const thumbnailPath = this._assetFor(message.assetPath)?.thumbnailPath;
        this._emit({
          type: 'thumbnail',
          assetPath: message.assetPath,
          source: thumbnailPath ? this._fileUrl(thumbnailPath) : null,
        });
        return;
      }

      case 'request-animation-data': {
        const asset = this._assetFor(message.assetPath);
        if (!asset) {
          this._emit({
            type: 'animation-data',
            assetPath: message.assetPath,
            preview: null,
            error: 'That asset is not in the current analysis.',
          });
          return;
        }
        // The document itself for a Lottie, so the harness *plays* it. Reviewing a
        // preview that cannot play proves nothing about the preview the IDEs ship.
        const document = LOTTIE_FORMATS.includes(asset.format)
          ? await this._get<{
              animation: unknown;
              totalFrames: number;
              frameRate: number;
            } | null>(`/api/lottie-document?assetPath=${encodeURIComponent(asset.path)}`)
          : null;

        this._emit({
          type: 'animation-data',
          assetPath: message.assetPath,
          preview: buildAnimationPreview({
            format: asset.format,
            sourceUrl: this._fileUrl(asset.path),
            stillUrl: asset.thumbnailPath ? this._fileUrl(asset.thumbnailPath) : null,
            animation: document?.animation ?? null,
            totalFrames: document?.totalFrames ?? 0,
            frameRate: document?.frameRate ?? 0,
          }),
          error: null,
        });
        return;
      }

      case 'save-preferences':
        this._preferences = { ...DEFAULT_PREFERENCES, ...message.preferences };
        writeStored('animoria.sandbox.preferences', this._preferences);
        this._emit({ type: 'preferences', preferences: this._preferences });
        return;

      case 'request-usage-references': {
        const response = await this._get<{
          references: readonly UsageReference[];
          complete: boolean;
        }>(`/api/usage-references?assetPath=${encodeURIComponent(message.assetPath)}`);
        this._emit({
          type: 'usage-references',
          assetPath: message.assetPath,
          references: response?.references ?? [],
          complete: response?.complete ?? false,
        });
        return;
      }

      case 'dismiss-cleanup-candidate':
        // Dismissal is view state, not a mutation of the workspace — the harness may
        // hold it for the same reason it holds a tab selection.
        if (message.dismissed) this._dismissed.add(message.assetPath);
        else this._dismissed.delete(message.assetPath);
        writeStored('animoria.sandbox.dismissed', [...this._dismissed]);
        await this._handle({ type: 'request-cleanup-proposal' });
        return;

      case 'request-cleanup-proposal': {
        const dismissed = [...this._dismissed].join('\n');
        const proposals = await this._get<RootCleanupProposal[]>(
          `/api/cleanup-proposal?dismissed=${encodeURIComponent(dismissed)}`
        );
        if (proposals) this._emit({ type: 'cleanup-proposal', roots: proposals });
        return;
      }

      case 'request-cleanup-plan': {
        const plans = await this._get<RootCleanupPlan[]>(
          `/api/cleanup-plan?paths=${encodeURIComponent(message.assetPaths.join('\n'))}`
        );
        if (plans) this._emit({ type: 'cleanup-plan', plans });
        return;
      }

      case 'request-resolution-plan': {
        const response = await this._get<{
          planId: string;
          plan: ResolutionPlan;
          rootId: string;
          rootName: string;
        }>(
          `/api/resolution-plan?groupId=${encodeURIComponent(
            message.groupId
          )}&keepPath=${encodeURIComponent(message.keepPath)}`
        );
        if (response) {
          this._emit({
            type: 'resolution-plan',
            planId: response.planId,
            plan: response.plan,
            rootId: response.rootId,
            rootName: response.rootName,
          });
        }
        return;
      }

      // ── Refused: everything that would mutate ──
      // Note these are *handled*, not omitted. The UI has already disabled the
      // control; a message arriving anyway means a bug or a hand-crafted call, and
      // silently ignoring it would make that bug invisible.
      case 'apply-cleanup-plan':
      case 'apply-resolution-plan':
      case 'restore-session':
      case 'request-trash-sessions':
        this._refuse(message.type);
        return;

      case 'generate-snippet': {
        // Real snippets, from Core's own registry. The harness exists to review the
        // screens the IDEs show, and a snippet panel with nothing in it reviews
        // nothing.
        const snippets = await this._get<
          readonly {
            label: string;
            language: string;
            code: string;
            imports: string | null;
            installHint: string | null;
          }[]
        >(`/api/snippets?assetPath=${encodeURIComponent(message.assetPath)}`);

        if (snippets && snippets.length > 0) {
          this._emit({ type: 'snippets', assetPath: message.assetPath, snippets });
        } else {
          this._emit({
            type: 'error',
            message: 'No snippet generator supports this asset.',
            recoverable: true,
          });
        }
        return;
      }

      case 'open-asset':
      case 'reveal-asset':
      case 'open-reference':
        // A harness has no editor to navigate. Logged so the flow is reviewable.
        this._log('host→ui', message.type, 'no-op: the Sandbox has no editor');
        return;

      case 'copy-to-clipboard':
        await navigator.clipboard?.writeText(message.text).catch(() => {
          this._log('refused', 'copy-to-clipboard', 'clipboard unavailable');
        });
        return;

      default: {
        // Exhaustive: an outbound message added to the contract without a case here
        // fails the build rather than vanishing at runtime, which is how
        // `request-animation-data` came to be handled by nobody.
        const unhandled: never = message;
        this._log('refused', (unhandled as HostOutbound).type, 'no handler in the Sandbox host');
        return;
      }
    }
  }

  /** The asset Core attributed to this path, or `null`. Never re-derived from the path. */
  private _assetFor(assetPath: string) {
    return this._analysis?.assets.find((entry) => entry.asset.path === assetPath)?.asset ?? null;
  }

  private _fileUrl(path: string): string {
    return `/api/file?path=${encodeURIComponent(path)}`;
  }

  private async _runAnalysis(): Promise<void> {
    this._emit({
      type: 'analysis-progress',
      readiness: {
        assetsIndexed: false,
        referencesResolved: false,
        duplicatesResolved: false,
        complete: false,
      },
      message: 'Indexing the fixture workspace…',
    });

    // `referenceCounts` is a `Map` in the contract and an array of pairs on the wire,
    // so the wire shape is named rather than cast away: `any` here would have hidden
    // the `AttributedAsset` mistake that made every thumbnail request miss.
    const analysis = await this._get<WireAnalysis>('/api/analysis');
    if (!analysis) return;

    const rehydrated: MultiRootAnalysis = {
      ...analysis,
      roots: analysis.roots.map((entry) => ({
        ...entry,
        analysis: {
          ...entry.analysis,
          referenceCounts: new Map(entry.analysis.referenceCounts ?? []),
        },
      })),
    };

    this._analysis = rehydrated;
    this._emit({ type: 'analysis', analysis: rehydrated });
  }

  private async _get<T>(url: string): Promise<T | null> {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        this._emit({
          type: 'error',
          message: `${url} responded ${response.status}. Is the dev bridge running?`,
          recoverable: true,
        });
        return null;
      }
      return (await response.json()) as T;
    } catch (err) {
      this._emit({
        type: 'error',
        message: err instanceof Error ? err.message : String(err),
        recoverable: true,
      });
      return null;
    }
  }
}

/** Reads one JSON value from `localStorage`, falling back rather than throwing. */
function readStored<T>(key: string, fallback: T): T {
  try {
    const raw = globalThis.localStorage?.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    // Malformed or unavailable storage is not worth a broken harness — but it is
    // worth a line, because silently reverting a developer's settings is the kind of
    // thing that gets reported as "it forgot my preferences again".
    console.warn(`[animoria-sandbox] could not read ${key}; using defaults`);
    return fallback;
  }
}

function writeStored(key: string, value: unknown): void {
  try {
    globalThis.localStorage?.setItem(key, JSON.stringify(value));
  } catch {
    console.warn(`[animoria-sandbox] could not persist ${key}`);
  }
}
