// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEventKind } from './AuditEventKind';

export type AuditEvent = {
  event_id: string;
  timestamp_ms: bigint;
  kind: AuditEventKind;
  actor: string;
  details: Record<string, unknown>;
};
