// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryScore } from './CategoryScore';

export type HealthScoreReport = {
  score: number;
  grade: string;
  categories: Array<CategoryScore>;
  summary: string;
};
