import type { GovernanceCheckReport } from '../governance-check-report.js';
import type { ReportRenderer } from './report-renderer.js';

/**
 * Renders a {@link GovernanceCheckReport} as GitHub-flavored Markdown,
 * suitable for posting as a pull request bot comment.
 *
 * This is one renderer among several (see `./renderer-registry.js`), not
 * the command's native output format — it exists because Markdown is
 * what most CI bots (GitHub Actions comment bots, GitLab MR widgets)
 * expect as an input, not because the check command's result is
 * conceptually Markdown-shaped.
 */
export const markdownRenderer: ReportRenderer = {
  format: 'markdown',

  render(report: GovernanceCheckReport): string {
    const lines: string[] = [];

    const badge = report.outcome.passed ? '✅ Passed' : '❌ Failed';
    lines.push(`## Animoria Governance Check — ${badge}`, '');
    lines.push('| Metric | Value |');
    lines.push('| :--- | :--- |');
    lines.push(`| Assets | ${report.totalAssetCount} |`);
    if (report.healthScore) {
      lines.push(`| Health Score | ${report.healthScore.score}/100 |`);
    }
    lines.push(`| Errors | ${report.diagnosticCountBySeverity.error} |`);
    lines.push(`| Warnings | ${report.diagnosticCountBySeverity.warning} |`);
    lines.push(`| Duration | ${Math.round(report.durationMs)}ms |`);
    lines.push('');

    if (report.configErrors.length > 0) {
      lines.push('### ⚠️ Configuration Problems', '');
      lines.push('| Rule | Problem |');
      lines.push('| :--- | :--- |');
      for (const error of report.configErrors) {
        lines.push(`| \`${error.ruleId}\` | ${error.errors.join('; ')} |`);
      }
      lines.push('');
    }

    if (report.diagnostics.length > 0) {
      lines.push('### Violations', '');
      lines.push('| Severity | Rule | Asset | Message |');
      lines.push('| :--- | :--- | :--- | :--- |');
      for (const diagnostic of report.diagnostics) {
        lines.push(
          `| ${diagnostic.severity} | \`${diagnostic.ruleId}\` | \`${diagnostic.asset.name}\` | ${diagnostic.message} |`
        );
      }
      lines.push('');
    }

    if (report.healthScore && report.healthScore.recommendations.length > 0) {
      lines.push('### Recommendations', '');
      for (const recommendation of report.healthScore.recommendations) {
        lines.push(`- ${recommendation.message}`);
      }
      lines.push('');
    }

    if (!report.outcome.passed) {
      lines.push('### Why this failed', '');
      for (const reason of report.outcome.failureReasons) {
        lines.push(`- ${reason}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Generated by Animoria at ${report.generatedAt}*`);

    return lines.join('\n');
  },
};
