import type { WorkspaceAnalysis } from '../analysis/workspace-analysis.js';
import { diagnosticCountBySeverity } from '../analysis/workspace-analysis.js';

/**
 * Renders a {@link WorkspaceAnalysis} as a self-contained governance document.
 *
 * Shared by every client's "export governance report" action, so the document a
 * VS Code user saves and the one a JetBrains user saves are byte-for-byte the same.
 *
 * ## Why this now takes the analysis
 * It used to render a `GovernanceReport` — the ad-hoc `unused` / `duplicate` /
 * `overused` classification produced by a second governance engine that fed nothing
 * into the Health Score. An exported report could therefore contradict the sidebar
 * that produced it. It now renders the same analysis every other surface consumes.
 */

function formatReportTimestamp(iso: string): string {
  const date = new Date(iso);
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: 'long',
    timeStyle: 'short',
  }).format(date);
}

function formatReportDuration(ms: number): string {
  return ms < 1000 ? `${Math.round(ms)} ms` : `${(ms / 1000).toFixed(2)} s`;
}

/** Renders a governance analysis as a self-contained Markdown document. */
export function buildMarkdownReport(analysis: WorkspaceAnalysis): string {
  const lines: string[] = [];
  const counts = diagnosticCountBySeverity(analysis);

  lines.push('# Animoria Governance Report', '');
  lines.push(`**Workspace:** \`${analysis.workspacePath}\`  `);
  lines.push(`**Generated:** ${formatReportTimestamp(analysis.generatedAt)}  `);
  lines.push(`**Analysis time:** ${formatReportDuration(analysis.durationMs)}`, '');

  lines.push('## Summary', '');
  lines.push('| Metric | Value |');
  lines.push('| :--- | ---: |');
  lines.push(`| Assets analyzed | ${analysis.assets.length} |`);
  lines.push(`| Findings | ${analysis.diagnostics.length} |`);
  lines.push(`| Errors | ${counts.error} |`);
  lines.push(`| Warnings | ${counts.warning} |`);
  lines.push(`| Duplicate groups | ${analysis.duplicateGroups.length} |`);
  lines.push(
    `| Health Score | ${
      analysis.health.status === 'computed'
        ? `${analysis.health.report.score}/100`
        : `not available — ${analysis.health.message}`
    } |`
  );
  lines.push('');

  if (analysis.health.status === 'computed' && analysis.health.report.qualifications.length > 0) {
    lines.push('> This score is qualified:', '>');
    for (const qualification of analysis.health.report.qualifications) {
      lines.push(`> - ${qualification.message}`);
    }
    lines.push('');
  }

  if (analysis.skippedRules.length > 0) {
    lines.push('## Rules that could not be evaluated', '');
    for (const skipped of analysis.skippedRules) {
      lines.push(`- \`${skipped.ruleId}\` (${skipped.severity}) — ${skipped.reason.message}`);
    }
    lines.push('');
  }

  if (analysis.diagnostics.length === 0) {
    lines.push('## Findings', '', 'No governance findings.', '');
  } else {
    lines.push('## Findings', '');
    for (const diagnostic of analysis.diagnostics) {
      lines.push(`### \`${diagnostic.asset.path}\``, '');
      lines.push(`- **Rule:** [\`${diagnostic.ruleId}\`](${diagnostic.helpUri})`);
      lines.push(`- **Severity:** ${diagnostic.severity}`);
      lines.push(`- **Confidence:** ${diagnostic.confidence}`);
      lines.push(`- **Evidence:** ${diagnostic.evidence.summary}`);
      if (diagnostic.coverage) {
        lines.push(
          `- **Coverage:** \`${diagnostic.coverage.status}\` (${diagnostic.coverage.filesScanned} file(s) scanned)`
        );
      }
      lines.push(`- **Fix:** ${diagnostic.remediation.summary}`, '');
    }
  }

  if (analysis.duplicateGroups.length > 0) {
    lines.push('## Duplicate groups', '');
    for (const group of analysis.duplicateGroups) {
      lines.push(
        `### \`${group.contentHash.slice(0, 12)}\` — ${group.candidates.length} identical files`,
        ''
      );
      for (const candidate of group.candidates) {
        lines.push(`- \`${candidate.asset.path}\` (${candidate.referenceCount} reference(s))`);
      }
      lines.push('');
    }
  }

  lines.push('---', '', '_Generated by Animoria._');
  return lines.join('\n');
}

/**
 * Serializes a governance analysis as JSON.
 *
 * `referenceCounts` is a `Map`, which `JSON.stringify` renders as `{}` — so it is
 * converted to entries explicitly rather than silently disappearing from every
 * exported report.
 */
export function buildJsonReport(analysis: WorkspaceAnalysis): string {
  return JSON.stringify(
    { ...analysis, referenceCounts: Array.from(analysis.referenceCounts.entries()) },
    null,
    2
  );
}
