import type { GovernanceReport } from '../types/asset.js';

/**
 * Renders a {@link GovernanceReport} (the ad-hoc unused/duplicate/overused
 * classification produced by `GovernanceAnalyzer`) as Markdown, or hands
 * back the report unmodified for JSON serialization.
 *
 * Shared by every client's "export governance report" action so the
 * document a VS Code user saves and the one a JetBrains user saves are
 * byte-for-byte the same format — this used to live duplicated inside
 * `animoria-vscode`.
 */

function formatReportTimestamp(iso: string): string {
  const date = new Date(iso);
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: 'long',
    timeStyle: 'short',
  }).format(date);
}

function formatReportDuration(ms: number): string {
  return ms < 1000 ? `${Math.round(ms)} ms` : `${(ms / 1000).toFixed(2)} s`;
}

/** Renders a governance report as a self-contained Markdown document. */
export function buildMarkdownReport(report: GovernanceReport): string {
  const lines: string[] = [];
  const total = report.unused.length + report.duplicates.length + report.overused.length;

  lines.push('# Animoria Governance Report', '');
  lines.push('| | |');
  lines.push('| :--- | :--- |');
  lines.push(`| **Generated** | ${formatReportTimestamp(report.generatedAt)} |`);
  lines.push(`| **Assets analyzed** | ${report.totalAssets} |`);
  lines.push(`| **Analysis duration** | ${formatReportDuration(report.durationMs)} |`);
  lines.push('');

  lines.push('## Summary', '');
  lines.push('| Category | Count |');
  lines.push('| :--- | ---: |');
  lines.push(`| Unused Assets | ${report.unused.length} |`);
  lines.push(`| Duplicate Assets | ${report.duplicates.length} |`);
  lines.push(`| Overused Assets | ${report.overused.length} |`);
  lines.push(`| **Total** | **${total}** |`);
  lines.push('');

  if (report.unused.length > 0) {
    lines.push('## Unused Assets', '');
    lines.push(
      '> These assets have no detected references in source files. Consider removing them to reduce bundle size.'
    );
    lines.push('');
    lines.push('| Asset | Path |');
    lines.push('| :--- | :--- |');
    for (const issue of report.unused) {
      lines.push(`| \`${issue.asset.name}\` | \`${issue.asset.path}\` |`);
    }
    lines.push('');
  }

  if (report.duplicates.length > 0) {
    lines.push('## Duplicate Assets', '');
    lines.push(
      '> These assets share identical file content. Keep one canonical copy and update references.'
    );
    lines.push('');
    lines.push('| Asset | Identical To | Path |');
    lines.push('| :--- | :--- | :--- |');
    for (const issue of report.duplicates) {
      const others = issue.duplicateOf?.map((a) => `\`${a.name}\``).join(', ') ?? '—';
      lines.push(`| \`${issue.asset.name}\` | ${others} | \`${issue.asset.path}\` |`);
    }
    lines.push('');
  }

  if (report.overused.length > 0) {
    lines.push('## Overused Assets', '');
    lines.push(
      '> These assets appear in many source files. Consider whether they should be centralized or split.'
    );
    lines.push('');
    lines.push('| Asset | References | Path |');
    lines.push('| :--- | ---: | :--- |');
    for (const issue of report.overused) {
      lines.push(`| \`${issue.asset.name}\` | ${issue.referenceCount} | \`${issue.asset.path}\` |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [Animoria](https://github.com/sxnnyside-project/animoria)*');

  return lines.join('\n');
}

/** Renders a governance report as pretty-printed JSON. */
export function buildJsonReport(report: GovernanceReport): string {
  return JSON.stringify(report, null, 2);
}
