build:
  maxIssues: 0
  excludeCorrectable: false

style:
  active: true
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false

complexity:
  active: true
  TooManyFunctions:
    active: false
  NestedBlockDepth:
    active: false

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
