import type { AnimoriaAsset, UsageReference } from '@animoria/core';
import type * as vscode from 'vscode';

// ── Reason taxonomy ───────────────────────────────────────────────────────────

/**
 * The reason(s) why an asset was included as a cleanup candidate.
 *
 * Extending this union is the *only* change required to introduce a new
 * category of cleanup opportunity. Add the literal here, then handle it
 * inside {@link CleanupPlanner} — no other file needs to change.
 */
export type CleanupReason =
  /** Zero high-confidence code references found. */
  | 'orphaned'
  /** File size exceeds the `.animoriarc` `max-file-size-kb` threshold. */
  | 'oversized'
  /** File format is not listed in `.animoriarc` `allowed-formats`. */
  | 'forbidden-format'
  /** Content hash is identical to at least one other asset in the workspace. */
  | 'duplicate'
  /** Filename or path matches a pattern associated with build-generated output. */
  | 'generated'
  /** Filename matches a naming convention indicating the file is temporary. */
  | 'temporary';

// ── Core domain types ─────────────────────────────────────────────────────────

/**
 * A single reviewable asset presented to the developer during a cleanup session.
 *
 * Every field that influences the developer's "keep or remove" decision must be
 * present here so the UI layer never needs to perform additional I/O.
 */
export interface CleanupCandidate {
  /** The underlying asset descriptor. */
  readonly asset: AnimoriaAsset;

  /**
   * One or more reasons this asset was flagged. An asset may satisfy
   * multiple reasons simultaneously (e.g. both `orphaned` and `oversized`).
   */
  readonly reasons: readonly CleanupReason[];

  /**
   * `'high'` when the asset has zero known references — the only
   * confidence level {@link CleanupExecutor} will actually remove. `'medium'`
   * means a reason other than `orphaned` (e.g. `oversized`, `temporary`)
   * flagged an asset that is still referenced elsewhere; it is shown for
   * awareness but is always rejected at execution time (see
   * `CleanupExecutor`'s safety invariants). `'low'` is reserved for future
   * heuristic-only classifications and is not currently produced.
   */
  readonly confidence: 'high' | 'medium' | 'low';

  /** Number of known code references to this asset, from the most recent index pass. */
  readonly referenceCount: number;

  /**
   * The reference list (file path + line number + source snippet) for
   * display in the review panel. Populated by `CleanupPlanner` for every
   * candidate with `referenceCount > 0`; always empty for orphaned
   * candidates, since there is nothing to list.
   */
  readonly affectedReferences: readonly UsageReference[];

  /** File size in bytes, duplicated from `asset.sizeBytes` for convenience. */
  readonly sizeBytes: number;

  /**
   * When `true` the developer previously chose "Never suggest again" for this
   * specific asset path.  Dismissed candidates are excluded from future
   * proposals until the user explicitly resets dismissals.
   */
  dismissed: boolean;
}

/**
 * The full, pre-computed cleanup proposal generated by {@link CleanupPlanner}.
 *
 * A proposal is *immutable* — it describes what *would* be cleaned up if the
 * developer approved everything.  No files are modified until the developer
 * explicitly approves a {@link CleanupSession}.
 *
 * Proposals are **deterministic**: given the same governance snapshot as input,
 * {@link CleanupPlanner} will always produce an identical proposal.
 */
export interface CleanupProposal {
  /** All candidates surfaced for developer review, excluding dismissed ones. */
  readonly candidates: readonly CleanupCandidate[];

  /**
   * Total bytes that would be reclaimed if every candidate were removed.
   * Presented as the primary headline metric in the proposal summary.
   */
  readonly totalSizeBytes: number;

  /**
   * Total number of source-code references that would be broken or need
   * updating if every candidate were removed.
   */
  readonly affectedReferencesCount: number;

  /**
   * Deduplicated list of workspace-relative parent directories that contain
   * at least one candidate.  Useful for spatial orientation in the review UI.
   */
  readonly affectedFolders: readonly string[];

  /**
   * Estimated health-score delta (positive integer) if every candidate is
   * approved.  E.g. `11` means the score would improve from 81 to 92.
   */
  readonly estimatedHealthScoreDelta: number;

  /**
   * Rough estimate (in ms) for executing the approved cleanup.  Derived from
   * candidate count and reference rewrite complexity.  Used only for display.
   */
  readonly estimatedExecutionMs: number;

  /**
   * ISO-8601 timestamp of when this proposal was generated.  Serves as a
   * staleness indicator — stale proposals are regenerated before execution.
   */
  readonly generatedAt: string;
}

// ── Per-candidate developer decisions ────────────────────────────────────────

/**
 * The decision a developer can make about a single cleanup candidate.
 *
 * - `'remove'`  — mark this asset for deletion in the current session.
 * - `'keep'`    — exclude from this session; may appear in future proposals.
 * - `'dismiss'` — exclude permanently; persisted via `workspaceState`.
 */
export type CandidateDecision = 'remove' | 'keep' | 'dismiss';

// ── Active session ────────────────────────────────────────────────────────────

/**
 * An active cleanup review session, binding a {@link CleanupProposal} to the
 * developer's per-candidate decisions and (once generated) to the pre-validated
 * {@link vscode.WorkspaceEdit} that will perform the actual mutations.
 *
 * **Lifecycle**
 * ```
 * CleanupPlanner.buildProposal()
 *   → CleanupSession (decisions all 'keep' by default)
 *   → developer reviews, sets decisions to 'remove' / 'keep' / 'dismiss'
 *   → CleanupExecutor.prepare(session) — generates workspaceEdit, validates
 *   → CleanupExecutor.execute(session) — applies edit + deletes files
 *   → CleanupSummary
 * ```
 *
 * The {@link workspaceEdit} is intentionally kept on this object rather than
 * constructed inside `execute()` so that the edit can be presented for
 * inspection (or cancelled) before any filesystem change occurs.
 */
export interface CleanupSession {
  /** The immutable proposal this session is reviewing. */
  readonly proposal: CleanupProposal;

  /**
   * Per-candidate decisions, keyed by `asset.path`.
   * Defaults to `'keep'` for every candidate until the developer acts.
   */
  decisions: Map<string, CandidateDecision>;

  /**
   * The pre-generated workspace edit, set by {@link CleanupExecutor.prepare}.
   * Present only after preparation and before execution.
   */
  workspaceEdit?: vscode.WorkspaceEdit;

  /**
   * Identifies the `.animoria/trash/<trashSessionId>/` directory
   * {@link workspaceEdit} will move approved candidates into, set by
   * {@link CleanupExecutor.prepare} alongside the edit. `undefined` when
   * the session has nothing to remove (a dismiss-only or no-op session
   * never needs a trash directory).
   */
  trashSessionId?: string | undefined;
}

// ── Execution result ──────────────────────────────────────────────────────────

/**
 * The result of a completed {@link CleanupSession} execution, used to
 * populate the post-cleanup summary screen.
 */
export interface CleanupSummary {
  /** Paths of assets successfully deleted from disk. */
  readonly removedAssetPaths: readonly string[];

  /** Total bytes reclaimed by this session. */
  readonly bytesReclaimed: number;

  /**
   * Number of source-code references rewritten by this session. Always
   * `0` — `CleanupExecutor` refuses to remove any candidate with a known
   * reference (see its safety invariants), so a Bulk Cleanup removal never
   * has a reference to rewrite. Present on this type for symmetry with
   * Assist Duplicate Resolution's summary, which does rewrite references.
   */
  readonly referencesUpdated: number;

  /**
   * Health-score before this session was executed (captured at proposal time).
   * Displayed as the "before" value in the summary diff.
   */
  readonly healthScoreBefore: number;

  /**
   * Estimated health-score after execution, derived from
   * `healthScoreBefore + proposal.estimatedHealthScoreDelta`.
   */
  readonly healthScoreAfter: number;

  /**
   * Number of cleanup candidates that remain after this session (i.e. those
   * the developer chose to keep).  Surfaced as "remaining opportunities".
   */
  readonly remainingCandidates: number;

  /** ISO-8601 timestamp of when this session completed. */
  readonly completedAt: string;

  /**
   * Absolute path to the `.animoria/trash/<sessionId>/` directory the
   * removed assets were moved into, or `null` when nothing was removed
   * (a dismiss-only session). This is the recovery mechanism's location —
   * see `CleanupTrash.ts` — surfaced so the summary screen can tell the
   * developer exactly where to look to undo this specific run.
   */
  readonly trashLocation: string | null;
}

// ── Persistence key ───────────────────────────────────────────────────────────

/**
 * VS Code `workspaceState` key under which dismissed asset paths are stored.
 *
 * Stored as a `string[]` of absolute asset paths.  Centralised here so
 * {@link CleanupPlanner} and the reset command both reference the same key.
 */
export const DISMISSED_ASSETS_STATE_KEY = 'animoria.cleanup.dismissed' as const;
