package com.sxnnyside.animoria.governance

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.testFramework.LightVirtualFile
import com.sxnnyside.animoria.backend.CoreProcessManager
import com.sxnnyside.animoria.backend.GovernanceReportExportData
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.put

/**
 * Opens the current governance report as a read-only Markdown document in
 * the editor. Content is generated by `@animoria/core`'s
 * `report-formatter.ts` via the `exportGovernanceReport` daemon command —
 * this object only requests it and opens the result. Mirrors VS Code's
 * `viewGovernanceReport()` / `markdown.showPreview`.
 */
object GovernanceReportEditor {
    fun open(project: Project) {
        val processManager = project.getService(CoreProcessManager::class.java)
        GlobalScope.launch(Dispatchers.IO) {
            try {
                val response =
                    processManager.sendCommand(
                        "exportGovernanceReport",
                        buildJsonObject { put("format", "markdown") },
                    )
                val result = Json.decodeFromJsonElement<GovernanceReportExportData>(response)

                ApplicationManager.getApplication().invokeLater {
                    if (result.error != null) {
                        Messages.showWarningDialog(project, result.error, "Governance Report")
                        return@invokeLater
                    }
                    val file = LightVirtualFile("Animoria Governance Report.md", result.content)
                    file.isWritable = false
                    FileEditorManager.getInstance(project).openFile(file, true)
                }
            } catch (e: Exception) {
                com.sxnnyside.animoria.logging.AnimoriaLogger.error("Animoria: Failed to open governance report", e)
            }
        }
    }
}
